"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
import django_stubs_ext
from dotenv import load_dotenv

django_stubs_ext.monkeypatch()

load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv('DEBUG', 'false').lower() in ('yes', '1', 'true')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


ALLOWED_HOSTS = tuple(os.getenv('ALLOWED_HOSTS', '').split()) or ()

CSRF_TRUSTED_ORIGINS = (
    tuple(os.getenv('CSRF_TRUSTED_ORIGINS', '').split()) or ()
)

INSTALLED_APPS = (
    'locale',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bulma',
    'task_manager',
    'task_manager.users',
    'task_manager.tasks',
    'task_manager.labels',
    'django_filters',
    'django_htmx',
)

if DEBUG:
    INSTALLED_APPS = INSTALLED_APPS + ('django_extensions',)

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

AUTH_USER_MODEL = 'users.User'

LOGIN_REDIRECT_URL = '/'

LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/login'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


def get_database_config():
    """Get database configuration based on environment."""
    if os.environ.get('GITHUB_WORKFLOW'):
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': 'github_actions',
                'USER': 'postgres',
                'PASSWORD': 'postgres',
                'HOST': '127.0.0.1',
                'PORT': '5432',
            },
        }

    if os.getenv('DATABASE_URL'):
        conn_max_age = 500
        return {
            'default': dj_database_url.config(conn_max_age=conn_max_age)  # type: ignore
        }

    return {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'postgres'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        },
    }


DATABASES = get_database_config()

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
)

ROOT_URLCONF = 'task_manager.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = (
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (TEMPLATE_DIR,),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': (
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'task_manager.context_processors.theme_mode',
                'task_manager.context_processors.registration_available',
            ),
        },
    },
)

WSGI_APPLICATION = 'task_manager.wsgi.application'


def get_rest_framework_config():
    """Get REST framework configuration."""
    return {
        'DEFAULT_FILTER_BACKENDS': (
            'django_filters.rest_framework.DjangoFilterBackend',
            ...,
        ),
    }


REST_FRAMEWORK = get_rest_framework_config()

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = (
    {
        'NAME': 'django.contrib.auth.password_validation'
        '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
)

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

LANGUAGES = (
    ('en', 'English'),
    ('ru', 'Russian'),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, 'task_manager/locale'),)

# Static image (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'app_data', 'files', 'static')
if not Path(STATIC_ROOT).exists():
    os.makedirs(STATIC_ROOT)
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'app_data', 'files', 'media')
if not Path(MEDIA_ROOT).exists():
    os.makedirs(MEDIA_ROOT)
MEDIA_URL = '/media/'

# Extra places for collectstatic to find static image.
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'task_manager/static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


def get_bootstrap4_config():
    """Get Bootstrap4 configuration."""
    return {
        'css_url': {
            'href': (
                'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/'
                'bootstrap.min.css'
            )
        },
        'javascript_url': {
            'url': (
                'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/'
                'bootstrap.bundle.min.js'
            )
        },
        'jquery_url': {'url': 'https://code.jquery.com/jquery-3.7.1.min.js'},
        'include_jquery': 'full',
        'horizontal_field_class': 'col-md-10 mb-1',
        'horizontal_label_class': 'col-md-2',
    }


BOOTSTRAP4 = get_bootstrap4_config()

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bulma',)
CRISPY_TEMPLATE_PACK = 'bulma'

# Secure
if not DEBUG:
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
