
name: task_manager

services:
  db:
    image: postgres:latest
    volumes:
      - ${LOCATION:-./app_data}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-task-manager}
    ports:
      - "5435:5432"
    restart: always
    networks:
      - default

  task-manager-server:
    container_name: task_manager_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne task_manager.asgi:application --port ${PORT:-8000} --bind 0.0.0.0 -v2"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/task-manager}
      SECRET_KEY: ${SECRET_KEY:-}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://127.0.0.1,http://localhost}
      CHAT_ID: ${CHAT_ID:-}
      BROKER_URL: ${BROKER_URL:-amqp://rabbitmq:rabbitmq@rabbitmq:5672/}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ_USER: ${RMUSER:-rabbitmq}
      RABBITMQ_PASS: ${RMPASSWORD:-rabbitmq}
      RABBITMQ_HOST: ${RMHOST:-rabbitmq}
      RABBITMQ_PORT: ${RMPORT:-5672}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    depends_on:
      - rabbitmq
      - redis
      - db
    restart: on-failure
    networks:
      - default

  worker-celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager_celery
    command: celery -A task_manager worker -l INFO --concurrency=4
    env_file:
      - .env
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    environment:
      BROKER_URL: ${BROKER_URL:-amqp://rabbitmq:rabbitmq@rabbitmq:5672/}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ_DEFAULT_USER: ${RMUSER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RMPASSWORD:-rabbitmq}
      RABBITMQ_DEFAULT_HOST: ${RMHOST:-rabbitmq}
      RABBITMQ_DEFAULT_PORT: ${RMPORT:-5672}
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure
    networks:
      - default

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager_celery_beat
    command: celery -A task_manager beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    environment:
      BROKER_URL: ${BROKER_URL:-amqp://rabbitmq:rabbitmq@rabbitmq:5672/}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ_DEFAULT_USER: ${RMUSER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RMPASSWORD:-rabbitmq}
      RABBITMQ_DEFAULT_HOST: ${RMHOST:-rabbitmq}
      RABBITMQ_DEFAULT_PORT: ${RMPORT:-5672}
    depends_on:
      - rabbitmq
      - redis
      - db
    restart: on-failure
    networks:
      - default

  flower:
    image: mher/flower:2.0.1
    container_name: task_manager_flower
    command: celery flower --broker=${BROKER_URL:-amqp://rabbitmq:rabbitmq@rabbitmq:5672/} --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure
    networks:
      - default

  redis:
    container_name: task_manager_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ${LOCATION:-./app_data}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  rabbitmq:
    container_name: task_manager_rabbitmq
    image: rabbitmq:4.1.3-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RMUSER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RMPASSWORD:-rabbitmq}
      RABBITMQ_DEFAULT_HOST: ${RMHOST:-rabbitmq}
      RABBITMQ_DEFAULT_PORT: ${RMPORT:-5672}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity" ]
      interval: 15s
      timeout: 15s
      retries: 10
    volumes:
      - ${LOCATION:-./app_data}/rabbitmq:/var/lib/rabbitmq
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: task_manager_nginx
    ports:
      - "${NGINX_PORT:-8000}:80"
    volumes:
      - ${CONF_PATH:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
      - ${LOCATION:-./app_data}:/app_data/files
    depends_on:
      - task-manager-server
    restart: ${RESTART:-always}
    networks:
      - default

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.34.0.0/16

volumes:
  app_data:
