
name: task_manager

services:
  db:
    image: postgres:latest
    volumes:
      - ${LOCATION:-app_data}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-task-manager}
#    ports:
#      - "5433:5432"
    restart: always
    networks:
      - default
  task-manager-server:
    container_name: task_manager_server
    image: ghcr.io/turtleold/task_manager:main
    volumes:
      - ${LOCATION:-app_data}:/app
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne task_manager.asgi:application --port ${PORT:-8000} --bind 0.0.0.0 -v2"
#    ports:
#      - "8001:8001"
#    expose:
#      - "8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/task-manager}
      SECRET_KEY: ${SECRET_KEY:-}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
    depends_on:
      - db
    restart: on-failure
    networks:
      - default

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.34.0.0/16
