
name: task_manager

services:
  db:
    image: postgres:latest
    volumes:
      - ${LOCATION:-./app_data}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-task-manager}
    ports:
      - "5435:5432"
    restart: always
    networks:
      - default

  task-manager-server:
    container_name: task_manager_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    command: sh -c "uv run python manage.py migrate --noinput && uv run python manage.py collectstatic --noinput && uv run daphne task_manager.asgi:application --port ${PORT:-8000} --bind 0.0.0.0 -v2"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/task-manager}
      SECRET_KEY: ${SECRET_KEY:-}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://127.0.0.1,http://localhost}
      CHAT_ID: ${CHAT_ID:-}
    depends_on:
      - db
    restart: on-failure
    networks:
      - default

  redis:
    container_name: task_manager_redis
    image: redis:8-alpine
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ${LOCATION:-./app_data}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: task_manager_nginx
    ports:
      - "${NGINX_PORT:-8000}:80"
    volumes:
      - ${CONF_PATH:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
      - ${LOCATION:-./app_data}:/app_data/files
    depends_on:
      - task-manager-server
    restart: ${RESTART:-always}
    networks:
      - default

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.34.0.0/16

volumes:
  app_data:
