# Generated by Django 6.0.2 on 2026-02-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_card_deadline_estimate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='card',
            new_name='kanban_card_column__f189d9_idx',
            old_name='kanban_car_column_p_idx',
        ),
        migrations.RenameIndex(
            model_name='column',
            new_name='kanban_colu_board_i_df05fd_idx',
            old_name='kanban_col_board_po_idx',
        ),
    ]
