# Generated by Django 6.0.2 on 2026-02-05 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_card_deadline_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="assigned_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="priority",
            field=models.CharField(blank=True, default="🟡", max_length=10),
        ),
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="card",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="card",
            name="checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="card",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
