# Generated by Django 6.0.2 on 2026-02-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_rename_kanban_car_column_p_idx_kanban_card_column__f189d9_idx_and_more'),
    ]

    operations: list[migrations.Operation] = []
