# Generated by Django 6.0.2 on 2026-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_card_tags_categories_models"),
        ("kanban", "0005_merge_20260205_1349"),
        ("kanban", "0004_card_extra_fields"),
    ]

    operations: list = []
