# Generated by Django 6.0.2 on 2026-02-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='kanban_noti_status_5a4a41_idx',
            old_name='kanban_noti_status_6a4db9_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='kanban_noti_user_id_88d9fa_idx',
            old_name='kanban_noti_user_id_8c35d4_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='kanban_noti_event_t_1cfe81_idx',
            old_name='kanban_noti_event_t_44ab77_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='kanban_noti_board_i_c04a43_idx',
            old_name='kanban_noti_board_i_1f28a3_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='kanban_noti_user_id_75cd48_idx',
            old_name='kanban_noti_user_id_e6f7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='kanban_noti_event_t_653c3e_idx',
            old_name='kanban_noti_event_t_4e1ea4_idx',
        ),
    ]
