# Generated by Django 6.0.2 on 2026-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0014_notification_push_channel"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="carddeadlinereminder",
            new_name="kanban_card_status_916681_idx",
            old_name="kanban_cardd_status_3a87b9_idx",
        ),
        migrations.RenameIndex(
            model_name="carddeadlinereminder",
            new_name="kanban_card_schedul_7f9dda_idx",
            old_name="kanban_cardd_scheduled_6f29e3_idx",
        ),
        migrations.RenameIndex(
            model_name="carddeadlinereminder",
            new_name="kanban_card_card_id_105d75_idx",
            old_name="kanban_cardd_card_us_8bd79d_idx",
        ),
        migrations.RenameIndex(
            model_name="carddeadlinereminderdelivery",
            new_name="kanban_card_status_2ac9d6_idx",
            old_name="kanban_cardd_status_4fcae2_idx",
        ),
        migrations.RenameIndex(
            model_name="carddeadlinereminderdelivery",
            new_name="kanban_card_reminde_8a155a_idx",
            old_name="kanban_cardd_rem_st_d7c91b_idx",
        ),
        migrations.RenameIndex(
            model_name="carddeadlinereminderdelivery",
            new_name="kanban_card_user_id_de884e_idx",
            old_name="kanban_cardd_user_ch_9cf0ef_idx",
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("column.created", "Column created"),
                    ("column.updated", "Column updated"),
                    ("column.deleted", "Column deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.moved", "Card moved"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("column.created", "Column created"),
                    ("column.updated", "Column updated"),
                    ("column.deleted", "Column deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.moved", "Card moved"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),
        ),
    ]
