# Generated by Django 6.0.3 on 2026-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kanban",
            "0015_rename_kanban_cardd_status_3a87b9_idx_kanban_card_status_916681_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overdue_reminder_interval",
                    models.IntegerField(
                        choices=[
                            (5, "5 минут"),
                            (10, "10 минут"),
                            (30, "30 минут"),
                            (60, "1 час"),
                        ],
                        default=30,
                        verbose_name="Интервал повторяющихся напоминаний",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.AddField(
            model_name="column",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
