# Generated by Django 6.0.5 on 2026-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0022_simplify_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='board',
            name='notification_telegram_chat_id',
        ),
    ]
