# Generated by Django 6.0.5 on 2026-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0028_checklist_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checklistitem',
            new_name='kanban_chec_card_id_f04499_idx',
            old_name='kanban_chec_card_id_idx',
        ),
        migrations.AddField(
            model_name='board',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
