# Generated by Django 6.0.5 on 2026-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0035_normalize_attachments"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attachment",
            new_name="kanban_atta_card_id_094604_idx",
            old_name="kanban_att_card_id_1b22c6_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="kanban_atta_uploade_d4b24a_idx",
            old_name="kanban_att_uploade_efecff_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="kanban_atta_type_f5134f_idx",
            old_name="kanban_att_type_927e81_idx",
        ),
        migrations.RenameIndex(
            model_name="card",
            new_name="kanban_card_parent__7aa12e_idx",
            old_name="kanban_card_parent__5f29f0_idx",
        ),
        migrations.RenameIndex(
            model_name="card",
            new_name="kanban_card_parent__080bc8_idx",
            old_name="kanban_card_parent__f6b36b_idx",
        ),
        migrations.RenameIndex(
            model_name="cardactivity",
            new_name="kanban_card_card_id_eaa02a_idx",
            old_name="kanban_card_card_id_9d5a1c_idx",
        ),
        migrations.RenameIndex(
            model_name="cardactivity",
            new_name="kanban_card_actor_i_85096a_idx",
            old_name="kanban_card_actor_i_580296_idx",
        ),
        migrations.RenameIndex(
            model_name="cardcomment",
            new_name="kanban_card_card_id_5eb701_idx",
            old_name="kanban_card_card_id_ebbc6c_idx",
        ),
        migrations.RenameIndex(
            model_name="cardcomment",
            new_name="kanban_card_author__336e8f_idx",
            old_name="kanban_card_author__4d3d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="recurrencerule",
            new_name="kanban_recu_next_du_044139_idx",
            old_name="kanban_recu_next_du_1d923b_idx",
        ),
        migrations.RenameIndex(
            model_name="recurrencerule",
            new_name="kanban_recu_freq_7e15e2_idx",
            old_name="kanban_recu_freq_4f1229_idx",
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("column.created", "Column created"),
                    ("column.updated", "Column updated"),
                    ("column.deleted", "Column deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.moved", "Card moved"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),  # noqa: E501
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("column.created", "Column created"),
                    ("column.updated", "Column updated"),
                    ("column.deleted", "Column deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.moved", "Card moved"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),  # noqa: E501
        ),
    ]
