# Generated by Django 6.0.5 on 2026-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kanban",
            "0036_rename_kanban_att_card_id_1b22c6_idx_kanban_atta_card_id_094604_idx_and_more",
        ),  # noqa: E501
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencerule",
            name="bysetpos",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
