# Generated by Django 6.0.5 on 2026-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0041_notification_inbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationprofile",
            name="unifiedpush_endpoint",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
