# Generated by Django on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0042_notification_profile_unifiedpush_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationprofile",
            name="fcm_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
