# Generated by Django 6.0.5 on 2026-08-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0045_dedupe_notification_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carddeadlinereminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("scheduled", "Scheduled"),
                    ("dispatched", "Dispatched"),
                    ("sent", "Sent"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("invalid.no_deadline", "Invalid: no deadline"),
                    ("invalid.past", "Invalid: time in past"),
                    ("invalid.channel", "Invalid: channel unavailable"),
                ],
                default="disabled",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="carddeadlinereminder",
            index=models.Index(
                fields=["status", "scheduled_at"], name="kanban_card_status_d41722_idx"
            ),
        ),
    ]
