# Generated by Django 6.0.5 on 2026-08-09 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0046_reminder_dispatched_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxschedule",
            new_name="kanban_inbo_status_e201ae_idx",
            old_name="kanban_inbo_status_4e801c_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxschedule",
            new_name="kanban_inbo_user_id_311963_idx",
            old_name="kanban_inbo_user_id_b40c49_idx",
        ),
    ]
