# Generated by Django 6.0.5 on 2026-08-15 15:53

from django.db import migrations, models

REMOVED_EVENT_TYPES = [
    "card.moved",
    "column.created",
    "column.updated",
    "column.deleted",
]


def delete_stale_preferences(apps, schema_editor):
    NotificationPreference = apps.get_model("kanban", "NotificationPreference")
    NotificationPreference.objects.filter(event_type__in=REMOVED_EVENT_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0049_backfill_completion_fields"),
    ]

    operations = [
        migrations.RunPython(delete_stale_preferences, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                ],
                max_length=50,
            ),
        ),
    ]
