# Generated by Django 6.0.7 on 2026-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0050_notification_event_vocabulary"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_shopping_list",
            field=models.BooleanField(default=False),
        ),
    ]
