# Generated by Django 6.0.7 on 2026-08-18 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0052_remove_column_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatcherHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="dispatcher", max_length=50, unique=True),
                ),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("ticks", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("webpush", "Web Push"),
                            ("fcm", "Firebase Cloud Messaging"),
                        ],
                        default="webpush",
                        max_length=20,
                    ),
                ),
                ("endpoint", models.URLField(blank=True, default="", max_length=1000)),
                ("p256dh", models.CharField(blank=True, default="", max_length=200)),
                ("auth", models.CharField(blank=True, default="", max_length=100)),
                ("token", models.CharField(blank=True, default="", max_length=512)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("failure_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["user_id", "-id"],
            },
        ),
        migrations.AddField(
            model_name="carddeadlinereminder",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="carddeadlinereminder",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="dispatch_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="dispatch_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="dispatch_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="dispatch_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="next_attempt_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["dispatch_status", "next_attempt_at"],
                name="kanban_noti_dispatc_ef2489_idx",
            ),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(fields=["user", "active"], name="kanban_push_user_id_6bd719_idx"),
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(fields=["kind", "active"], name="kanban_push_kind_547b64_idx"),
        ),
        migrations.AddConstraint(
            model_name="pushdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "webpush")),
                fields=("endpoint",),
                name="uniq_push_device_webpush_endpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "fcm")),
                fields=("token",),
                name="uniq_push_device_fcm_token",
            ),
        ),
    ]
