# Generated by Django 6.0.7 on 2026-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0054_migrate_push_tokens_and_seal_outbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatcherheartbeat",
            name="last_prune_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
