# Generated by Django 6.0.7 on 2026-08-18 16:28

from django.db import migrations, models


def delete_legacy_devices_and_preferences(apps, schema_editor):
    """Remove data that belonged to channels that no longer exist (ADR 0003).

    Legacy Android (FCM) devices are deleted, not deactivated: they can never
    receive Web Push, so keeping them would only add noise to the first
    delivery diagnosis. Notification preferences for email/Telegram are dropped
    along with the channels themselves.
    """

    PushDevice = apps.get_model("kanban", "PushDevice")
    NotificationPreference = apps.get_model("kanban", "NotificationPreference")

    PushDevice.objects.filter(kind="fcm").delete()
    NotificationPreference.objects.filter(channel__in=["email", "telegram"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0055_dispatcher_prune_timestamp"),
    ]

    operations = [
        migrations.RunPython(
            delete_legacy_devices_and_preferences,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="pushdevice",
            name="uniq_push_device_fcm_token",
        ),
        migrations.RemoveField(
            model_name="carddeadlinereminder",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="fcm_token",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="onesignal_player_id",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="telegram_chat_id",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="unifiedpush_endpoint",
        ),
        migrations.AlterField(
            model_name="carddeadlinereminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("scheduled", "Scheduled"),
                    ("dispatched", "Dispatched"),
                    ("sent", "Sent"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("invalid.no_deadline", "Invalid: no deadline"),
                    ("invalid.past", "Invalid: time in past"),
                    ("invalid.channel", "Invalid: no devices"),
                ],
                default="disabled",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="carddeadlinereminderdelivery",
            name="channel",
            field=models.CharField(choices=[("push", "Push")], max_length=20),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel",
            field=models.CharField(choices=[("push", "Push")], max_length=20),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="channel",
            field=models.CharField(choices=[("push", "Push")], max_length=20),
        ),
        migrations.AlterField(
            model_name="pushdevice",
            name="kind",
            field=models.CharField(
                choices=[("webpush", "Web Push")], default="webpush", max_length=20
            ),
        ),
        migrations.RemoveField(
            model_name="pushdevice",
            name="token",
        ),
    ]
