# Generated by Django 6.0.7 on 2026-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0056_remove_legacy_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatcherheartbeat",
            name="last_maintenance_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
