# Generated by Django 6.0.7 on 2026-09-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0057_dispatcherheartbeat_last_maintenance_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdelivery",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
