# Generated by Django 6.0.7 on 2026-09-25 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0058_notificationdelivery_dedupe_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                    ("card.overdue", "Card overdue"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                    ("card.overdue", "Card overdue"),
                ],
                max_length=50,
            ),
        ),
    ]
