# Generated by Django 6.0.7 on 2026-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0059_card_created_by_alter_notificationevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.archived", "Card archived"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                    ("card.overdue", "Card overdue"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("board.created", "Board created"),
                    ("board.updated", "Board updated"),
                    ("board.deleted", "Board deleted"),
                    ("card.created", "Card created"),
                    ("card.updated", "Card updated"),
                    ("card.deleted", "Card deleted"),
                    ("card.archived", "Card archived"),
                    ("card.completed", "Card completed"),
                    ("comment.created", "Comment created"),
                    ("card.deadline_reminder", "Card deadline reminder"),
                    ("card.overdue", "Card overdue"),
                ],
                max_length=50,
            ),
        ),
    ]
