# Generated by Django 6.0.8 on 2026-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0065_pushdevice_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatcherheartbeat",
            name="last_session_cleanup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
