# Generated by Django 4.0.4 on 2024-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add theme_mode field to User model.

    Adds a theme_mode field to allow users to choose between
    light and dark themes.
    """

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(
                choices=[('dark', 'dark'), ('light', 'light')],
                default='dark',
                max_length=10,
            ),
        ),
    ]
