# Generated by Django 5.1.2 on 2024-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(
                choices=[('dark', 'dark'), ('light', 'light')],
                default='dark',
                max_length=10,
            ),
        ),
    ]
