# Generated by Django 5.1.3 on 2024-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(
                choices=[(1, 'dark'), (2, 'light')], default='dark'
            ),
        ),
    ]
