# Generated by Django 5.1.3 on 2024-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(
                choices=[('dark', 'dark'), ('light', 'light')], default='dark'
            ),
        ),
    ]
