# Generated by Django 4.0.4 on 2024-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add theme_color field to User model.

    Adds a theme_color field to allow users to choose their
    preferred color scheme for the interface.
    """

    dependencies = [
        ('users', '0002_user_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(
                choices=[
                    ('red', 'Красный'),
                    ('orange', 'Оранжевый'),
                    ('yellow', 'Желтый'),
                    ('green', 'Зеленый'),
                    ('blue', 'Синий'),
                    ('indigo', 'Индиго'),
                    ('purple', 'Фиолетовый'),
                ],
                default='blue',
                help_text='Выберите основной цвет для интерфейса',
                max_length=10,
                verbose_name='Цвет темы',
            ),
        ),
    ]
