# Generated by Django 5.2.5 on 2025-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
