# Generated by Django 5.2.5 on 2025-08-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0002_alter_label_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderPeriod',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'period',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, '10 минут'),
                            (20, '20 минут'),
                            (30, '30 минут'),
                            (40, '40 минут'),
                            (50, '50 минут'),
                            (60, '1 час'),
                            (120, '2 часа'),
                            (180, '3 часа'),
                            (240, '4 часа'),
                            (300, '5 часов'),
                            (360, '6 часов'),
                            (420, '7 часов'),
                            (480, '8 часов'),
                            (540, '9 часов'),
                            (600, '10 часов'),
                            (660, '11 часов'),
                            (720, '12 часов'),
                            (780, '13 часов'),
                            (840, '14 часов'),
                            (900, '15 часов'),
                            (960, '16 часов'),
                            (1020, '17 часов'),
                            (1080, '18 часов'),
                            (1140, '19 часов'),
                            (1200, '20 часов'),
                            (1260, '21 час'),
                            (1320, '22 часа'),
                            (1380, '23 часа'),
                            (1440, '24 часа'),
                        ],
                        default=60,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        default='Process',
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                (
                    'checklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='tasks.checklist',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='images',
                        verbose_name='Изображение',
                    ),
                ),
                ('slug', models.SlugField(null=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'executor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='works',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'labels',
                    models.ManyToManyField(
                        blank=True, related_name='tasks', to='labels.label'
                    ),
                ),
                (
                    'reminder_periods',
                    models.ManyToManyField(
                        blank=True,
                        related_name='tasks',
                        to='tasks.reminderperiod',
                    ),
                ),
                (
                    'stage',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='tasks.stage',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment_content',
                    models.TextField(verbose_name='Содержание комментария'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(default=False, verbose_name='Удалён'),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='tasks.task',
                        verbose_name='Задача',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist',
                to='tasks.task',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['stage', 'order'], name='tasks_task_stage_i_2ae44f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['created_at'], name='tasks_task_created_be1ba2_idx'
            ),
        ),
    ]
