# Generated by Django 5.1.7 on 2025-07-25 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['stage', 'order'], name='tasks_task_stage_i_2ae44f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['created_at'], name='tasks_task_created_be1ba2_idx'
            ),
        ),
    ]
