# Generated by Django 5.2.5 on 2025-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_periods',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_periods',
            field=models.CharField(
                blank=True,
                help_text='Comma-separated list of reminder period values',
                max_length=255,
                null=True,
            ),
        ),
    ]
