# Generated by Django 5.2.5 on 2025-08-31 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_change_reminder_periods_to_charfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderPeriod',
        ),
    ]
