# Generated by Django 5.2.4 on 2025-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дата обновления'
            ),
        ),
    ]
