# Generated by Django 5.2.5 on 2025-08-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_reminderperiod_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sent_notifications',
            field=models.TextField(
                blank=True,
                help_text='JSON field to track sent notification periods',
                null=True,
            ),
        ),
    ]
