# Generated by Django 5.2.5 on 2025-08-13 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_alter_comment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
    ]
