# Generated by Django 5.2.5 on 2025-08-30 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('labels', '0002_alter_label_options'),
        ('tasks', '0005_fix_comment_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='reminderperiod',
            options={
                'verbose_name': 'Период напоминания',
                'verbose_name_plural': 'Периоды напоминания',
            },
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_content',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='text',
            field=models.CharField(
                default='Default checklist item',
                max_length=200,
                verbose_name='Текст',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(
                default='Default comment content', verbose_name='Содержание'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminderperiod',
            name='name',
            field=models.CharField(
                default='Default reminder period',
                max_length=50,
                verbose_name='Название',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist',
                to='tasks.task',
                verbose_name='Задача',
            ),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='tasks.checklist',
                verbose_name='Чек-лист',
            ),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminderperiod',
            name='period',
            field=models.IntegerField(
                default=24, verbose_name='Период в часах'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(
                default='Default Stage', max_length=100, verbose_name='Название'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дедлайн'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assigned_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнитель',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='images/',
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                blank=True,
                related_name='tasks',
                to='labels.label',
                verbose_name='Метки',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_periods',
            field=models.ManyToManyField(
                blank=True,
                to='tasks.reminderperiod',
                verbose_name='Периоды напоминания',
            ),
        ),
        # Alter existing slug field to add unique constraint
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(
                max_length=200, unique=True, blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='tasks.stage',
                verbose_name='Этап',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
