# Generated by Django 5.2.5 on 2025-08-30 19:14

from django.db import migrations
from transliterate import slugify


def populate_slug_field(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        if not task.slug:
            # Generate slug from task name
            base_slug = slugify(task.name)
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness by adding counter if needed
            while Task.objects.filter(slug=slug).exclude(id=task.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            task.slug = slug
            task.save(update_fields=['slug'])


def reverse_populate_slug_field(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_checklistitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_slug_field,
            reverse_populate_slug_field,
        ),
    ]
