# Generated by Django 5.2.5 on 2025-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_populate_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(
                max_length=200, unique=True, blank=True
            ),
        ),
    ]
