# Generated by Django 5.1.2 on 2024-10-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_reminderperiod_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'task',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checklist',
                        to='tasks.task',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                (
                    'checklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='tasks.checklist',
                    ),
                ),
            ],
        ),
    ]
