# Generated by Django 5.1.2 on 2024-11-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='files',
            new_name='image',
        ),
    ]
