# Generated by Django 5.1.3 on 2024-11-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='images',
                verbose_name='Изображение',
            ),
        ),
    ]
