# Generated by Django 5.1.3 on 2024-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_reminderperiod_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(unique=True)),
            ],
        ),
    ]
