# Generated by Django 5.1.7 on 2025-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_stage_options_stage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(
                blank=True,
                default='Process',
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
