name: PWA Build and Release

on:
  push:
    branches: [ "main" ]
    # Temporarily removed paths filter for debugging
    # paths:
    #   - 'pwa/**'
    #   - '.github/workflows/pwa-build.yml'
  pull_request:
    branches: [ "main" ]
    # Temporarily removed paths filter for debugging
    # paths:
    #   - 'pwa/**'
    #   - '.github/workflows/pwa-build.yml'
  release:
    types: [ published ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.35.3'
  PWA_DIR: './pwa'

jobs:
  build:
    name: Build PWA
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify repository checkout
        run: |
          echo "Repository root contents:"
          ls -la
          echo "Checking for .gitmodules:"
          if [ -f ".gitmodules" ]; then
            echo "✅ .gitmodules found"
            cat .gitmodules
          fi
          echo "Checking for PWA directory:"
          if [ -d "./pwa" ]; then
            echo "✅ PWA directory found"
            ls -la ./pwa
            echo "Checking for pubspec.yaml in PWA directory:"
            if [ -f "./pwa/pubspec.yaml" ]; then
              echo "✅ pubspec.yaml found in PWA directory"
              echo "First 10 lines of pubspec.yaml:"
              head -10 ./pwa/pubspec.yaml
            else
              echo "❌ pubspec.yaml not found in PWA directory!"
              echo "Contents of PWA directory:"
              find ./pwa -type f | head -20
            fi
          else
            echo "❌ PWA directory not found!"
            echo "Available directories:"
            find . -maxdepth 2 -type d
            echo "Checking if PWA files exist elsewhere:"
            find . -name "pubspec.yaml" -type f
            echo "Trying to initialize submodules manually..."
            git submodule update --init --recursive
            if [ -d "./pwa" ] && [ -f "./pwa/pubspec.yaml" ]; then
              echo "✅ PWA submodule loaded successfully after manual init"
            else
              echo "❌ Failed to load PWA submodule"
              exit 1
            fi
          fi

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Verify PWA directory structure
        run: |
          echo "Checking PWA directory structure..."
          ls -la ${{ env.PWA_DIR }}
          echo "Checking for pubspec.yaml..."
          if [ -f "${{ env.PWA_DIR }}/pubspec.yaml" ]; then
            echo "✅ pubspec.yaml found"
            cat ${{ env.PWA_DIR }}/pubspec.yaml | head -10
          else
            echo "❌ pubspec.yaml not found!"
            exit 1
          fi
          echo "Checking Flutter installation..."
          flutter --version
          echo "Checking Dart SDK version:"
          dart --version
          echo "Flutter doctor check:"
          flutter doctor --verbose

      - name: Clean Flutter cache (if needed)
        working-directory: ${{ env.PWA_DIR }}
        run: |
          echo "Cleaning Flutter cache..."
          flutter clean || true
          flutter pub cache clean || true

      - name: Check Dart SDK compatibility
        working-directory: ${{ env.PWA_DIR }}
        run: |
          echo "Checking Dart SDK compatibility..."
          DART_VERSION=$(dart --version | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)
          echo "Current Dart SDK version: $DART_VERSION"
          
          # Check if Dart version meets the requirement (^3.9.2)
          if [ "$(echo "$DART_VERSION" | cut -d. -f1)" -lt 3 ] || 
             ([ "$(echo "$DART_VERSION" | cut -d. -f1)" -eq 3 ] && [ "$(echo "$DART_VERSION" | cut -d. -f2)" -lt 9 ]) ||
             ([ "$(echo "$DART_VERSION" | cut -d. -f1)" -eq 3 ] && [ "$(echo "$DART_VERSION" | cut -d. -f2)" -eq 9 ] && [ "$(echo "$DART_VERSION" | cut -d. -f3)" -lt 2 ]); then
            echo "❌ Dart SDK version $DART_VERSION does not meet requirement ^3.9.2"
            echo "Please update Flutter version in workflow to get a newer Dart SDK"
            exit 1
          else
            echo "✅ Dart SDK version $DART_VERSION meets requirement ^3.9.2"
          fi

      - name: Get Flutter dependencies
        working-directory: ${{ env.PWA_DIR }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Flutter root: $FLUTTER_ROOT"
          echo "Flutter path: $(which flutter)"
          echo "Contents of current directory:"
          ls -la
          echo "Running flutter pub get..."
          
          # Try different approaches to get dependencies
          if ! flutter pub get --verbose; then
            echo "First attempt failed, trying alternative approach..."
            # Check if we're in the right directory
            if [ ! -f "pubspec.yaml" ]; then
              echo "pubspec.yaml not found in current directory, listing contents:"
              ls -la
              exit 1
            fi
            # Try with explicit path
            flutter pub get --verbose --directory .
          fi

      - name: Verify Flutter installation
        working-directory: ${{ env.PWA_DIR }}
        run: flutter doctor

      - name: Run Flutter tests
        working-directory: ${{ env.PWA_DIR }}
        run: flutter test

      - name: Build PWA for web
        working-directory: ${{ env.PWA_DIR }}
        run: |
          flutter build web \
            --release \
            --web-renderer html \
            --dart-define=FLUTTER_WEB_USE_SKIA=false \
            --base-href="/pwa/"

      - name: Upload PWA build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pwa-web-build
          path: ${{ env.PWA_DIR }}/build/web/
          retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download PWA build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: pwa-web-build
          path: ./pwa-release

      - name: Create release archive
        run: |
          cd pwa-release
          tar -czf ../pwa-web-release.tar.gz .
          zip -r ../pwa-web-release.zip .

      - name: Upload release assets
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pwa-release-assets
          path: |
            pwa-web-release.tar.gz
            pwa-web-release.zip
          retention-days: 90

      - name: Create GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: |
            pwa-web-release.tar.gz
            pwa-web-release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download PWA build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: pwa-web-build
          path: ./pwa-preview

      - name: Deploy to GitHub Pages (Preview)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pwa-preview
          destination_dir: pwa-preview/pr-${{ github.event.number }}
          keep_files: false

      - name: Comment PR with preview URL
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 PWA Preview deployed: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pwa-preview/pr-${{ github.event.number }}/'
            })

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Run Flutter security analysis
        working-directory: ${{ env.PWA_DIR }}
        run: |
          flutter pub deps
          flutter analyze --fatal-infos

      - name: Check for known vulnerabilities
        working-directory: ${{ env.PWA_DIR }}
        run: |
          flutter pub audit

  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download PWA build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: pwa-web-build
          path: ./pwa-test

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x

      - name: Run Lighthouse CI
        run: |
          if [ -n "$LHCI_GITHUB_APP_TOKEN" ]; then
            lhci autorun --upload.target=temporary-public-storage
          else
            echo "LHCI_GITHUB_APP_TOKEN not set, skipping upload"
            lhci autorun --upload.target=filesystem
          fi
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build, release, deploy-preview, security-scan, performance-test]
    if: always()
    
    steps:
      - name: Notify on success
        if: ${{ needs.build.result == 'success' && needs.security-scan.result == 'success' && needs.performance-test.result == 'success' }}
        run: |
          echo "✅ PWA build completed successfully!"
          echo "Build artifacts are available for download."
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "🚀 Release assets have been created and uploaded."
          fi
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "🔍 Preview deployment is available for review."
          fi

      - name: Notify on failure
        if: ${{ needs.build.result == 'failure' || needs.security-scan.result == 'failure' || needs.performance-test.result == 'failure' }}
        run: |
          echo "❌ PWA build failed!"
          echo "Please check the logs for details."
          exit 1
